{
 "title": "Nomad",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius\n", "legendFormat": "{{chip}}" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_cpu_frequency_hertz{job=\"nomad\"}[5m]) / 1e9)"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " (irate(node_disk_read_time_seconds_total[5m]))"
    },
    {
     "expr": " (irate(node_disk_write_time_seconds_total[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "(irate(node_disk_io_time_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (mode) (irate(node_cpu_seconds_total{job=\"nomad\"}[$interval])) * 100) / 4",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" },
    { "expr": "node_memory_Active_bytes", "legendFormat": "Active" },
    { "expr": "node_memory_Inactive_bytes", "legendFormat": "Inactive" },
    { "expr": "node_memory_SwapCached_bytes", "legendFormat": "Swap Cached" },
    { "expr": "node_memory_Dirty_bytes", "legendFormat": "Dirty" },
    { "expr": "node_memory_Committed_AS_bytes", "legendFormat": "Committed" }
   ]
  },
  {
   "title": "Memory Resident",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(namedprocess_namegroup_memory_bytes{memtype=\"resident\"})",
     "legendFormat": "{{groupname}}"
    },
    { "expr": "cpu" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}